=== ChoCoBo1712/epam-xml/src/main/resources/schema/devices.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.example.com/devices"
        xmlns:tns="http://www.example.com/devices"
        elementFormDefault="qualified">

    <element name="devices">
        <complexType>
            <sequence>
                <element ref="tns:device" maxOccurs="unbounded" />
            </sequence>
        </complexType>
    </element>
    <element name="device" type="tns:device" abstract="true"/>
    <element name="peripheral-device" type="tns:peripheral-device" substitutionGroup="tns:device"/>
    <element name="integral-device" type="tns:integral-device" substitutionGroup="tns:device"/>

    <complexType name="device">
        <sequence>
            <element name="name" type="string"/>
            <element name="origin" type="tns:origin"/>
            <element name="price">
                <simpleType>
                    <restriction base="unsignedInt">
                        <minInclusive value="1"/>
                        <maxInclusive value="1000000"/>
                    </restriction>
                </simpleType>
            </element>
            <element name="release-time" type="gYearMonth"/>
            <element name="power-consumption">
                <simpleType>
                    <restriction base="unsignedInt">
                        <minInclusive value="1"/>
                        <maxInclusive value="10000"/>
                    </restriction>
                </simpleType>
            </element>
            <element name="cooler" type="boolean"/>
            <element name="critical" type="boolean"/>
        </sequence>
        <attribute name="id" type="tns:device-id" use="required"/>
        <attribute name="color" type="string" use="optional" default="Black"/>
    </complexType>
    
    <complexType name="peripheral-device">
        <complexContent>
            <extension base="tns:device">
                <sequence>
                    <element name="port" type="tns:port"/>
                    <element name="peripheral-type" type="tns:peripheral-type"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>
    
    <complexType name="integral-device">
        <complexContent>
            <extension base="tns:device">
                <sequence>
                    <element name="integral-type" type="tns:integral-type"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>
    
    <simpleType name="origin">
        <restriction base="string">
            <enumeration value="USA"/>
            <enumeration value="China"/>
            <enumeration value="Japan"/>
            <enumeration value="Germany"/>
        </restriction>
    </simpleType>

    <simpleType name="device-id">
        <restriction base="ID">
            <pattern value="\w{1,20}"/>
        </restriction>
    </simpleType>

    <simpleType name="port">
        <restriction base="string">
            <enumeration value="COM"/>
            <enumeration value="USB"/>
            <enumeration value="LPT"/>
        </restriction>
    </simpleType>

    <simpleType name="integral-type">
        <restriction base="string">
            <enumeration value="CPU"/>
            <enumeration value="Motherboard"/>
            <enumeration value="Power supply"/>
        </restriction>
    </simpleType>

    <simpleType name="peripheral-type">
        <restriction base="string">
            <enumeration value="IO"/>
            <enumeration value="Multimedia"/>
        </restriction>
    </simpleType>
</schema>

=== ChoCoBo1712/epam-xml/src/test/resources/data/valid.xml
<?xml version="1.0" encoding="UTF-8"?>
<devices xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://www.example.com/devices"
         xsi:schemaLocation="http://www.example.com/devices ../schema/devices.xsd">

    <peripheral-device device-id="peripheral1" color="Blue">
        <name>Peripheral example</name>
        <origin>USA</origin>
        <price>100</price>
        <release-time>2020-12</release-time>
        <power-consumption>100</power-consumption>
        <cooler>false</cooler>
        <critical>true</critical>
        <port>USB</port>
        <peripheral-type>IO</peripheral-type>
    </peripheral-device>

    <peripheral-device device-id="peripheral2" color="Blue">
        <name>Peripheral example</name>
        <origin>USA</origin>
        <price>100</price>
        <release-time>2020-12</release-time>
        <power-consumption>100</power-consumption>
        <cooler>false</cooler>
        <critical>true</critical>
        <port>USB</port>
        <peripheral-type>IO</peripheral-type>
    </peripheral-device>

    <peripheral-device device-id="peripheral3" color="Blue">
        <name>Peripheral example</name>
        <origin>USA</origin>
        <price>100</price>
        <release-time>2020-12</release-time>
        <power-consumption>100</power-consumption>
        <cooler>false</cooler>
        <critical>true</critical>
        <port>USB</port>
        <peripheral-type>IO</peripheral-type>
    </peripheral-device>

    <peripheral-device device-id="peripheral4" color="Blue">
        <name>Peripheral example</name>
        <origin>USA</origin>
        <price>100</price>
        <release-time>2020-12</release-time>
        <power-consumption>100</power-consumption>
        <cooler>false</cooler>
        <critical>true</critical>
        <port>USB</port>
        <peripheral-type>IO</peripheral-type>
    </peripheral-device>

    <peripheral-device device-id="peripheral5" color="Blue">
        <name>Peripheral example</name>
        <origin>USA</origin>
        <price>100</price>
        <release-time>2020-12</release-time>
        <power-consumption>100</power-consumption>
        <cooler>false</cooler>
        <critical>true</critical>
        <port>USB</port>
        <peripheral-type>IO</peripheral-type>
    </peripheral-device>

    <peripheral-device device-id="peripheral6" color="Blue">
        <name>Peripheral example</name>
        <origin>USA</origin>
        <price>100</price>
        <release-time>2020-12</release-time>
        <power-consumption>100</power-consumption>
        <cooler>false</cooler>
        <critical>true</critical>
        <port>USB</port>
        <peripheral-type>IO</peripheral-type>
    </peripheral-device>

    <peripheral-device device-id="peripheral7" color="Blue">
        <name>Peripheral example</name>
        <origin>USA</origin>
        <price>100</price>
        <release-time>2020-12</release-time>
        <power-consumption>100</power-consumption>
        <cooler>false</cooler>
        <critical>true</critical>
        <port>USB</port>
        <peripheral-type>IO</peripheral-type>
    </peripheral-device>

    <peripheral-device device-id="peripheral8" color="Blue">
        <name>Peripheral example</name>
        <origin>USA</origin>
        <price>100</price>
        <release-time>2020-12</release-time>
        <power-consumption>100</power-consumption>
        <cooler>false</cooler>
        <critical>true</critical>
        <port>USB</port>
        <peripheral-type>IO</peripheral-type>
    </peripheral-device>

    <integral-device device-id="integral1">
        <name>Integral example</name>
        <origin>CHINA</origin>
        <price>1000</price>
        <release-time>2016-11</release-time>
        <power-consumption>1000</power-consumption>
        <cooler>true</cooler>
        <critical>true</critical>
        <integral-type>CPU</integral-type>
    </integral-device>

    <integral-device device-id="integral2">
        <name>Integral example</name>
        <origin>CHINA</origin>
        <price>1000</price>
        <release-time>2016-11</release-time>
        <power-consumption>1000</power-consumption>
        <cooler>true</cooler>
        <critical>true</critical>
        <integral-type>CPU</integral-type>
    </integral-device>

    <integral-device device-id="integral3">
        <name>Integral example</name>
        <origin>CHINA</origin>
        <price>1000</price>
        <release-time>2016-11</release-time>
        <power-consumption>1000</power-consumption>
        <cooler>true</cooler>
        <critical>true</critical>
        <integral-type>CPU</integral-type>
    </integral-device>

    <integral-device device-id="integral4">
        <name>Integral example</name>
        <origin>CHINA</origin>
        <price>1000</price>
        <release-time>2016-11</release-time>
        <power-consumption>1000</power-consumption>
        <cooler>true</cooler>
        <critical>true</critical>
        <integral-type>CPU</integral-type>
    </integral-device>

    <integral-device device-id="integral5">
        <name>Integral example</name>
        <origin>CHINA</origin>
        <price>1000</price>
        <release-time>2016-11</release-time>
        <power-consumption>1000</power-consumption>
        <cooler>true</cooler>
        <critical>true</critical>
        <integral-type>CPU</integral-type>
    </integral-device>

    <integral-device device-id="integral6">
        <name>Integral example</name>
        <origin>CHINA</origin>
        <price>1000</price>
        <release-time>2016-11</release-time>
        <power-consumption>1000</power-consumption>
        <cooler>true</cooler>
        <critical>true</critical>
        <integral-type>CPU</integral-type>
    </integral-device>

    <integral-device device-id="integral7">
        <name>Integral example</name>
        <origin>CHINA</origin>
        <price>1000</price>
        <release-time>2016-11</release-time>
        <power-consumption>1000</power-consumption>
        <cooler>true</cooler>
        <critical>true</critical>
        <integral-type>CPU</integral-type>
    </integral-device>

    <integral-device device-id="integral8">
        <name>Integral example</name>
        <origin>CHINA</origin>
        <price>1000</price>
        <release-time>2016-11</release-time>
        <power-consumption>1000</power-consumption>
        <cooler>true</cooler>
        <critical>true</critical>
        <integral-type>CPU</integral-type>
    </integral-device>

</devices>

=== ChoCoBo1712/epam-xml/src/main/resources/data/devices.xml
<?xml version="1.0" encoding="UTF-8"?>
<devices xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://www.example.com/devices"
         xsi:schemaLocation="http://www.example.com/devices ../schema/devices.xsd">

    <peripheral-device id="peripheral1">
        <name>Peripheral example 1</name>
        <origin>USA</origin>
        <price>100</price>
        <power-consumption>100</power-consumption>
        <cooler>false</cooler>
        <critical>true</critical>
        <port>USB</port>
        <type>IO</type>
    </peripheral-device>

    <peripheral-device id="peripheral2">
        <name>Peripheral example 2</name>
        <origin>China</origin>
        <price>300</price>
        <power-consumption>200</power-consumption>
        <cooler>false</cooler>
        <critical>false</critical>
        <port>COM</port>
        <type>Multimedia</type>
    </peripheral-device>

    <peripheral-device id="peripheral3">
        <name>Peripheral example 3</name>
        <origin>Japan</origin>
        <price>400</price>
        <power-consumption>150</power-consumption>
        <cooler>true</cooler>
        <critical>false</critical>
        <port>LPT</port>
        <type>IO</type>
    </peripheral-device>

    <peripheral-device id="peripheral4">
        <name>Peripheral example 4</name>
        <origin>Germany</origin>
        <price>1000</price>
        <power-consumption>330</power-consumption>
        <cooler>true</cooler>
        <critical>true</critical>
        <port>COM</port>
        <type>IO</type>
    </peripheral-device>

    <peripheral-device id="peripheral5">
        <name>Peripheral example 5</name>
        <origin>Germany</origin>
        <price>600</price>
        <power-consumption>50</power-consumption>
        <cooler>false</cooler>
        <critical>false</critical>
        <port>USB</port>
        <type>Multimedia</type>
    </peripheral-device>

    <peripheral-device id="peripheral6">
        <name>Peripheral example 6</name>
        <origin>China</origin>
        <price>199</price>
        <power-consumption>60</power-consumption>
        <cooler>true</cooler>
        <critical>false</critical>
        <port>LPT</port>
        <type>Multimedia</type>
    </peripheral-device>

    <peripheral-device id="peripheral7">
        <name>Peripheral example 7</name>
        <origin>Japan</origin>
        <price>700</price>
        <power-consumption>150</power-consumption>
        <cooler>true</cooler>
        <critical>false</critical>
        <port>COM</port>
        <type>Multimedia</type>
    </peripheral-device>

    <peripheral-device id="peripheral8">
        <name>Peripheral example 8</name>
        <origin>USA</origin>
        <price>1500</price>
        <power-consumption>500</power-consumption>
        <cooler>true</cooler>
        <critical>false</critical>
        <port>USB</port>
        <type>IO</type>
    </peripheral-device>

    <integral-device id="integral1">
        <name>Integral example 1</name>
        <origin>China</origin>
        <price>1000</price>
        <power-consumption>1000</power-consumption>
        <cooler>true</cooler>
        <critical>true</critical>
        <type>CPU</type>
    </integral-device>

    <integral-device id="integral2">
        <name>Integral example 2</name>
        <origin>USA</origin>
        <price>500</price>
        <power-consumption>300</power-consumption>
        <cooler>false</cooler>
        <critical>true</critical>
        <type>Motherboard</type>
    </integral-device>

    <integral-device id="integral3">
        <name>Integral example 3</name>
        <origin>Japan</origin>
        <price>400</price>
        <power-consumption>50</power-consumption>
        <cooler>false</cooler>
        <critical>true</critical>
        <type>Power supply</type>
    </integral-device>

    <integral-device id="integral4">
        <name>Integral example 4</name>
        <origin>Germany</origin>
        <price>5000</price>
        <power-consumption>800</power-consumption>
        <cooler>true</cooler>
        <critical>true</critical>
        <type>CPU</type>
    </integral-device>

    <integral-device id="integral5">
        <name>Integral example 5</name>
        <origin>USA</origin>
        <price>100</price>
        <power-consumption>100</power-consumption>
        <cooler>true</cooler>
        <critical>true</critical>
        <type>CPU</type>
    </integral-device>

    <integral-device id="integral6">
        <name>Integral example 6</name>
        <origin>China</origin>
        <price>200</price>
        <power-consumption>150</power-consumption>
        <cooler>false</cooler>
        <critical>true</critical>
        <type>Motherboard</type>
    </integral-device>

    <integral-device id="integral7">
        <name>Integral example 7</name>
        <origin>Japan</origin>
        <price>600</price>
        <power-consumption>450</power-consumption>
        <cooler>true</cooler>
        <critical>true</critical>
        <type>CPU</type>
    </integral-device>

    <integral-device id="integral8">
        <name>Integral example 8</name>
        <origin>Japan</origin>
        <price>666</price>
        <power-consumption>100</power-consumption>
        <cooler>false</cooler>
        <critical>true</critical>
        <type>Power supply</type>
    </integral-device>
    
</devices>
